name: app_lorry
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.1

dependencies:
  badges: ^3.1.2
  bluetooth_classic: ^0.0.1
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.8.0
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  provider: ^6.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  toastification: ^3.0.1

dev_dependencies:
  build_runner: 2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/app_logo/prod/Icon_App.png'
  adaptive_icon_background: 'assets/app_logo/prod/Icon_App_Bg.png'
  adaptive_icon_foreground: 'assets/app_logo/prod/Icon_App_Fg.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_logo/
    - assets/app_logo/prod/
    - assets/app_logo/dev/
    - assets/app_logo/qa/
    - assets/icons/
    - assets/icons/services/
    - lib/config/env/.env.dev
    - lib/config/env/.env.qa
    - lib/config/env/.env.prod

